### ISSUE TITLE
How to close chat?

### ISSUE THREAD

**Issue by ikonovalenko** [LiveHelperChat/fbmessenger#1]
Hello,

If you close chat from admin interface and facebook user sends you a new messages, you will never see those messages. How can I close chat correctly?

**Comment by remdex** [comment]
I'll take care of that case. In new realease. Just wait for an hour :)

**Comment by remdex** [comment]
Fixed. In new version. It will make chat pending again. Not sure is it the best option. Need to gather feedback :)
