### ISSUE TITLE
bot can not reply fbmessenger

### ISSUE THREAD

**Issue by redneurocom** [LiveHelperChat/fbmessenger#13]
i see the reply in bot widget reply list but not in Facebook messenger, how can i solve it?

**Comment by remdex** [comment]
Hi,
That's correct. At the moment FB Messenger is not supported. It's possible to develop, but i'm just overloaded with commercial tasks...

**Comment by redneurocom** [comment]
ok i see, but.. in settings my pages you put a checkbox with bot so i think is related to generic bot., and what will be the cost to add fb support ? maybe you can send me to jpuma@redneurocom.com

**Comment by remdex** [comment]
Implemented. Basic bot support.
https://github.com/LiveHelperChat/fbmessenger/commit/0d7c965ce0bed604228a19d771d79d95b7c5e914
