### ISSUE TITLE
(#12) Requires version v3.2 or higher

### ISSUE THREAD

**Issue by premhunt** [LiveHelperChat/fbmessenger#20]
I am getting error "(#12) Requires version v3.2 or higher", when click on subscribe button.
I have done composer update also.
![image](https://user-images.githubusercontent.com/3192603/92866514-4067e100-f41d-11ea-9db2-2f577608669a.png)

**Comment by remdex** [comment]
It's an error about facebook API version of the app itself. Please update API version in facebook developer console.
