### ISSUE TITLE
Random fail on query

### ISSUE THREAD

**Issue by DevDorrejo** [LiveHelperChat/fbmessenger#21]
hello i am getting this error randomly

A query failed internally in Persistent Object: SQLSTATE[42000]: Syntax error or access violation: 1142 UPDATE command denied to user 'db'@'localhost' for table 'lhc_fbmessenger_page' Query: 'UPDATE `lhc_fbmessenger_page` SET `dep_id` = :ezcValue1, `page_token` = :ezcValue2, `verify_token` = :ezcValue3, `app_secret` = :ezcValue4, `name` = :ezcValue5, `verified` = :ezcValue6, `bot_disabled` = :ezcValue7 WHERE `id` = :ezcValue8'

**Comment by remdex** [comment]
This issue I can't reproduce so can't fix.

**Comment by DevDorrejo** [comment]
Hello, executing again the sql using the cron.php fix this issue.
