### ISSUE TITLE
Message from LHC to FB not work

### ISSUE THREAD

**Issue by DevDorrejo** [LiveHelperChat/fbmessenger#23]
Hello, i have a setup that is giving the next error and not send message from LHC to FB
![image](https://user-images.githubusercontent.com/7697566/95141402-16b18980-073f-11eb-8aec-a5857f53c356.png)

but from FB to the LHC work perfectly
![image](https://user-images.githubusercontent.com/7697566/95141552-8758a600-073f-11eb-8efa-506207b815f6.png)

Bot config:
Removed because of security.

Apache error_log [chat_error_log.txt](https://github.com/LiveHelperChat/fbmessenger/files/5330597/chat_error_log.txt)

cache/default.log: ***Empty***

**Comment by remdex** [comment]
Sorry, but here all works. Please while developing disable cache, because from compiled files not much I can do.
