### ISSUE TITLE
Debug Output

### ISSUE THREAD

**Issue by Boffice** [LiveHelperChat/fbmessenger#24]
Hello, i get not found errors in my debug output for multiple tpl files, same issue with twilio extension.

Not Found /lhc_web/extension/fbmessenger/design/fbmessengertheme/tpl/lhsystem/configuration.tpl.php
Not Found /lhc_web/extension/fbmessenger/design/fbmessengertheme/tpl/lhsystem/configuration_titles/system_title.tpl.php
Not Found /lhc_web/extension/fbmessenger/design/fbmessengertheme/tpl/lhsystem/configuration_tabs/generate_js.tpl.php

There are more files, if needed i will collect and report all of them.

**Comment by remdex** [comment]
Hi,
This is fine. As long it finds the templates after checking various paths. In debug output it just writes where it tried to find a file.
