### ISSUE TITLE
Support for receiving audio message from Facebook

### ISSUE THREAD

**Issue by alonsoac** [LiveHelperChat/fbmessenger#34]
It is needed to make a change like this in several places of bootstrap.php:
          if ($data['type'] == 'file') {
                        $messageText .= '[url=' . $data['payload']['url'].']Download file[/url]';
                    **} else if ($data['type'] == 'audio') {
                        $messageText .= '[url=' . $data['payload']['url'].']Audio[/url]';**
                    } else if ($data['type'] == 'image') {

Adding the 2 lines in bold to show an Audio link which can be clicked to download and listen to audio. If it could be played directly on browser that would be even better.

**Comment by remdex** [comment]
AT the moment I did as you just URL to download, with more effort would be possible to have it as audio E.g

You can try this if you want :). Not tested by me :)
```
[html]<audio preload="none" style="width: 230px" controls><source src="' . $data['payload']['url'] . '" type="audio/ogg"></audio> [/html]
```
