### ISSUE TITLE
chat pnd_time is not set on new chat

### ISSUE THREAD

**Issue by alonsoac** [LiveHelperChat/fbmessenger#37]
New chat comes from FB. chat.pnd_time is set to 0.   This for example causes condition like {time}-{args.chat.pnd_time} > 60  to be true immediately on new chat.

**Comment by remdex** [comment]
Thius is related to your webhook configuration. Not related to extension. Extend your check that it would ignore facebook chats.

**Comment by alonsoac** [comment]
We do not want to ignore FB chats, we want to know how long they have been pending. Isn't pnd_time supposed to be set on any kind of chat?

**Comment by remdex** [comment]
You can try changes I just pushed, perhaps will help. If not you will have to check that it's not FB chat just :)
