### ISSUE TITLE
integration with a Rasa bot does not work

### ISSUE THREAD

**Issue by pvizcaya** [LiveHelperChat/fbmessenger#40]
The scenario when Facebook (Whatsapp) user send a message and that land on agent or bot of LHC, works fine.  But the scenario when the Whatsapp user send a message and that is routing to Rasa bot, dos not work.
Same Rasa bot works fine with MessageBird integration.
Do you have any tip or upgrade or example that works in that scenario?
Tx 
Paulo

**Comment by remdex** [comment]
Sorry, but all works here. You will have todo some debugging to figure out that yourself...
