### ISSUE TITLE
Fresh install error: We’ll be back soon!

### ISSUE THREAD

**Issue by ChaseNL** [LiveHelperChat/fbmessenger#41]
Installed by documentation but receive this error page if click from "Admin > Modules > Facebook chat" "We’ll be back soon!" log says only this error:

`Sep 16 18:39:36 [Warning] [default] [default] Facebook\Exceptions\FacebookSDKException Object
(
    [message:protected] => Required "app_id" key not supplied in config and could not find fallback environment variable "FACEBOOK_APP_ID"
    [string:Exception:private] => Facebook\Exceptions\FacebookSDKException: Required "app_id" key not supplied in config and could not find fallback environment variable "FACEBOOK_APP_ID" in /home/test/domains/support.testps.com/public_html/extension/fbmessenger/vendor/facebook/graph-sdk/src/Facebook/Facebook.php:139
Stack trace:
#0 /home/test/domains/support.testps.com/public_html/extension/fbmessenger/classes/erlhcoreclassmodelfbuser.php(34): Facebook\Facebook->__construct()
#1 /home/test/domains/support.testps.com/public_html/cache/compiledtemplates/220ea90f186af9a85b2362baa890f8f5.php(1): erLhcoreClassModelFBMessengerUser::getFBAppInstance()
#2 /home/test/domains/support.testps.com/public_html/lib/core/lhtpl/tpl.php(572): include('/home/test/...')
#3 /home/test/domains/support.testps.com/public_html/lib/core/lhtpl/tpl.php(545): erLhcoreClassTemplate->fetchExecute()
#4 /home/test/domains/support.testps.com/public_html/cache/compiledtemplates/b8ce1a179e2ebd6e1bc5ccf76a50c391.php(2): erLhcoreClassTemplate->fetch()
#5 /home/test/domains/support.testps.com/public_html/lib/core/lhcore/lhmodule.php(108): include('/home/test/...')
#6 /home/test/domains/support.testps.com/public_html/lib/core/lhcore/lhmodule.php(658): erLhcoreClassModule::runModule()
#7 /home/test/domains/support.testps.com/public_html/index.php(53): erLhcoreClassModule::moduleInit()
#8 {main}
    [code:protected] => 0
    [file:protected] => /home/test/domains/support.testps.com/public_html/extension/fbmessenger/vendor/facebook/graph-sdk/src/Facebook/Facebook.php
    [line:protected] => 139
    [trace:Exception:private] => Array
        (
            [0] => Array
                (
                    [file] => /home/test/domains/support.testps.com/public_html/extension/fbmessenger/classes/erlhcoreclassmodelfbuser.php
                    [line] => 34
                    [function] => __construct
                    [class] => Facebook\Facebook
                    [type] => ->
                )

            [1] => Array
                (
                    [file] => /home/test/domains/support.testps.com/public_html/cache/compiledtemplates/220ea90f186af9a85b2362baa890f8f5.php
                    [line] => 1
                    [function] => getFBAppInstance
                    [class] => erLhcoreClassModelFBMessengerUser
                    [type] => ::
                )

            [2] => Array
                (
                    [file] => /home/test/domains/support.testps.com/public_html/lib/core/lhtpl/tpl.php
                    [line] => 572
                    [args] => Array
                        (
                            [0] => /home/test/domains/support.testps.com/public_html/cache/compiledtemplates/220ea90f186af9a85b2362baa890f8f5.php
                        )

                    [function] => include
                )

            [3] => Array
                (
                    [file] => /home/test/domains/support.testps.com/public_html/lib/core/lhtpl/tpl.php
                    [line] => 545
                    [function] => fetchExecute
                    [class] => erLhcoreClassTemplate
                    [type] => ->
                )

            [4] => Array
                (
                    [file] => /home/test/domains/support.testps.com/public_html/cache/compiledtemplates/b8ce1a179e2ebd6e1bc5ccf76a50c391.php
                    [line] => 2
                    [function] => fetch
                    [class] => erLhcoreClassTemplate
                    [type] => ->
                )

            [5] => Array
                (
                    [file] => /home/test/domains/support.testps.com/public_html/lib/core/lhcore/lhmodule.php
                    [line] => 108
                    [args] => Array
                        (
                            [0] => /home/test/domains/support.testps.com/public_html/cache/compiledtemplates/b8ce1a179e2ebd6e1bc5ccf76a50c391.php
                        )

                    [function] => include
                )

            [6] => Array
                (
                    [file] => /home/test/domains/support.testps.com/public_html/lib/core/lhcore/lhmodule.php
                    [line] => 658
                    [function] => runModule
                    [class] => erLhcoreClassModule
                    [type] => ::
                )

            [7] => Array
                (
                    [file] => /home/test/domains/support.testps.com/public_html/index.php
                    [line] => 53
                    [function] => moduleInit
                    [class] => erLhcoreClassModule
                    [type] => ::
                )

        )

    [previous:Exception:private] => 
)`

**Comment by remdex** [comment]
Install composer dependencies as required.
